import type { ResumeEntry, ResumeSection, SourceResume } from "./schema";

const forbiddenPatterns = [
  /\\documentclass\b/i,
  /\\usepackage\b/i,
  /\\(?:input|include)\s*\{/i,
  /\\write18\b/i,
  /\\(?:openout|read|write|immediate)\b/i,
  /\\begin\s*\{document\}/i,
  /\\end\s*\{document\}/i,
];

export function validateLatexBody(source: string): string[] {
  const errors: string[] = [];
  for (const pattern of forbiddenPatterns) {
    if (pattern.test(source)) errors.push("Paste only the resume body; preambles, file imports, and executable commands are not supported.");
  }
  const environmentStack: string[] = [];
  for (const match of source.matchAll(/\\(begin|end)\s*\{([^}]+)\}/g)) {
    if (match[1] === "begin") environmentStack.push(match[2]);
    else if (environmentStack.pop() !== match[2]) { environmentStack.push("mismatch"); break; }
  }
  if (environmentStack.length) errors.push("The LaTeX environments appear unbalanced. Check each \\begin and \\end pair.");
  let depth = 0;
  let escaped = false;
  for (const char of source) {
    if (char === "\\" && !escaped) { escaped = true; continue; }
    if (char === "{" && !escaped) depth += 1;
    if (char === "}" && !escaped) depth -= 1;
    if (depth < 0) break;
    escaped = false;
  }
  if (depth !== 0) errors.push("The LaTeX braces appear unbalanced.");
  return [...new Set(errors)];
}

export function escapeLatex(value: string): string {
  return value
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}");
}

function safeUrl(value: string): string {
  try {
    const url = new URL(value);
    if (url.protocol !== "http:" && url.protocol !== "https:") return "";
    return url.toString();
  } catch { return ""; }
}

function renderEntry(entry: ResumeEntry, type: ResumeSection["type"]): string {
  const bullets = entry.bullets.length
    ? `\n      \\resumeItemListStart\n${entry.bullets.map((bullet) => `        \\resumeItem{${escapeLatex(bullet.text)}}`).join("\n")}\n      \\resumeItemListEnd`
    : "";

  if (type === "projects") {
    return `    \\resumeProjectHeading\n      {\\textbf{${escapeLatex(entry.heading)}}${entry.subheading ? ` $|$ \\emph{${escapeLatex(entry.subheading)}}` : ""}}{${escapeLatex(entry.date)}}${bullets}`;
  }
  return `    \\resumeSubheading\n      {${escapeLatex(entry.heading)}}{${escapeLatex(entry.location)}}\n      {${escapeLatex(entry.subheading)}}{${escapeLatex(entry.date)}}${bullets}`;
}

function renderSection(section: ResumeSection): string {
  if (!section.entries.length) return "";
  if (section.type === "skills") {
    const content = section.entries.flatMap((entry) => entry.bullets.map((bullet) => bullet.text)).filter(Boolean).join(" • ");
    return `\\section{${escapeLatex(section.title)}}\n \\begin{itemize}[leftmargin=0.15in, label={}]\n    \\small{\\item{${escapeLatex(content)}}}\n \\end{itemize}`;
  }
  const listName = section.type === "projects" ? "Project" : "SubHeading";
  return `\\section{${escapeLatex(section.title)}}\n  \\resume${listName}ListStart\n${section.entries.map((entry) => renderEntry(entry, section.type)).join("\n")}\n  \\resume${listName}ListEnd`;
}

export function renderJakeResume(resume: SourceResume): string {
  const contactParts = [resume.contact.phone, resume.contact.email, ...resume.contact.links.map((link) => link.label)].filter(Boolean);
  const links = resume.contact.links.map((link) => {
    const url = safeUrl(link.url);
    return url ? `\\href{${url}}{\\underline{${escapeLatex(link.label)}}}` : escapeLatex(link.label);
  });
  const headerParts = [resume.contact.phone ? escapeLatex(resume.contact.phone) : "", resume.contact.email ? `\\href{mailto:${escapeLatex(resume.contact.email)}}{\\underline{${escapeLatex(resume.contact.email)}}}` : "", ...links].filter(Boolean);
  const summary = resume.summary.trim() ? `\\section{Summary}\n\\small{${escapeLatex(resume.summary.trim())}}` : "";
  const sections = resume.sections.map(renderSection).filter(Boolean).join("\n\n");
  void contactParts;

  return `%-------------------------
% Resume in LaTeX
% Template author: Jake Gutierrez
% Based on: https://github.com/sb2nov/resume
% Original template license: MIT
% Generated by Proofread using evidence supplied by the user
%------------------------
\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}
\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}
\\urlstyle{same}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}
\\titleformat{\\section}{\\vspace{-4pt}\\scshape\\raggedright\\large}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]
\\pdfgentounicode=1

\\newcommand{\\resumeItem}[1]{\\item\\small{{#1 \\vspace{-2pt}}}}
\\newcommand{\\resumeSubheading}[4]{\\vspace{-2pt}\\item\\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}\\textbf{#1} & #2 \\\\ \\textit{\\small#3} & \\textit{\\small #4} \\\\ \\end{tabular*}\\vspace{-7pt}}
\\newcommand{\\resumeProjectHeading}[2]{\\item\\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}\\small#1 & #2 \\\\ \\end{tabular*}\\vspace{-7pt}}
\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}
\\newcommand{\\resumeProjectListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeProjectListEnd}{\\end{itemize}}

\\begin{document}

\\begin{center}
    \\textbf{\\Huge \\scshape ${escapeLatex(resume.contact.name || "Your Name")}} \\\\ \\vspace{1pt}
    \\small ${headerParts.join(" $|$ ")}
\\end{center}

${summary ? `${summary}\n\n` : ""}${sections}

\\end{document}
`;
}

export function safeFilename(name: string, company: string, role: string): string {
  const clean = (value: string) => value.trim().replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return [clean(name) || "Resume", clean(company), clean(role)].filter(Boolean).join("_").slice(0, 120) + ".tex";
}

export function estimateOverflow(resume: SourceResume): boolean {
  const bulletCount = resume.sections.flatMap((section) => section.entries).reduce((sum, entry) => sum + entry.bullets.length, 0);
  const charCount = JSON.stringify(resume).length;
  return bulletCount > 18 || charCount > 8_500;
}
